


export default function Page(){

    return(
        <div className="min-h-[calc(100vh-5rem)]  mt-[4.5em]   text-justify p-5 m-2 ">
          <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum voluptatibus laboriosam exercitationem dolores iusto voluptatem provident a hic obcaecati possimus unde consequuntur nulla voluptate minus similique odit, perspiciatis dolor et distinctio sunt aut autem veritatis dignissimos dicta. Nesciunt quasi repellat perferendis tempora consequuntur eius laborum quisquam sint. Veritatis harum ut praesentium? Quibusdam architecto esse pariatur adipisci beatae totam corporis earum, possimus odio laboriosam Repellendus quae, laudantium dignissimos sapiente dolor dolores ipsa quia alias deleniti eius pariatur unde distinctio! Incidunt officia eum quae dignissimos alias ducimus blanditiis maxime debitis nobis quibusdam, architecto ex voluptas?0</h1>
          <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum voluptatibus laboriosam exercitationem dolores iusto voluptatem provident a hic obcaecati possimus unde consequuntur nulla voluptate minus similique odit, perspiciatis dolor et distinctio sunt aut autem veritatis dignissimos dicta. Nesciunt quasi repellat perferendis tempora consequuntur eius laborum quisquam sint. Veritatis harum ut praesentium? Quibusdam architecto esse pariatur adipisci beatae totam corporis earum, possimus odio laboriosam Repellendus quae, laudantium dignissimos sapiente dolor dolores ipsa quia alias deleniti eius pariatur unde distinctio! Incidunt officia eum quae dignissimos alias ducimus blanditiis maxime debitis nobis quibusdam, architecto ex voluptas?1</h1>
          <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum voluptatibus laboriosam exercitationem dolores iusto voluptatem provident a hic obcaecati possimus unde consequuntur nulla voluptate minus similique odit, perspiciatis dolor et distinctio sunt aut autem veritatis dignissimos dicta. Nesciunt quasi repellat perferendis tempora consequuntur eius laborum quisquam sint. Veritatis harum ut praesentium? Quibusdam architecto esse pariatur adipisci beatae totam corporis earum, possimus odio laboriosam Repellendus quae, laudantium dignissimos sapiente dolor dolores ipsa quia alias deleniti eius pariatur unde distinctio! Incidunt officia eum quae dignissimos alias ducimus blanditiis maxime debitis nobis quibusdam, architecto ex voluptas?2</h1>
          <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum voluptatibus laboriosam exercitationem dolores iusto voluptatem provident a hic obcaecati possimus unde consequuntur nulla voluptate minus similique odit, perspiciatis dolor et distinctio sunt aut autem veritatis dignissimos dicta. Nesciunt quasi repellat perferendis tempora consequuntur eius laborum quisquam sint. Veritatis harum ut praesentium? Quibusdam architecto esse pariatur adipisci beatae totam corporis earum, possimus odio laboriosam Repellendus quae, laudantium dignissimos sapiente dolor dolores ipsa quia alias deleniti eius pariatur unde distinctio! Incidunt officia eum quae dignissimos alias ducimus blanditiis maxime debitis nobis quibusdam, architecto ex voluptas?3</h1>
          <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum voluptatibus laboriosam exercitationem dolores iusto voluptatem provident a hic obcaecati possimus unde consequuntur nulla voluptate minus similique odit, perspiciatis dolor et distinctio sunt aut autem veritatis dignissimos dicta. Nesciunt quasi repellat perferendis tempora consequuntur eius laborum quisquam sint. Veritatis harum ut praesentium? Quibusdam architecto esse pariatur adipisci beatae totam corporis earum, possimus odio laboriosam Repellendus quae, laudantium dignissimos sapiente dolor dolores ipsa quia alias deleniti eius pariatur unde distinctio! Incidunt officia eum quae dignissimos alias ducimus blanditiis maxime debitis nobis quibusdam, architecto ex voluptas?4</h1>
        </div>
    )
}